CREATE TABLE tb_template (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    template_file BYTEA NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT DEFAULT 1,
    is_active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE tb_document (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    template_id INT REFERENCES tb_template(id) ON DELETE SET NULL,
    pdf_content BYTEA NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT DEFAULT 1,
    is_active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE tb_user (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT DEFAULT 1,
    is_active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE tb_signature (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    document_id INT REFERENCES tb_document(id) ON DELETE CASCADE,
    user_id INT REFERENCES tb_user(id) ON DELETE SET NULL,
    signature_type VARCHAR(50) NOT NULL,
    signature_content BYTEA NOT NULL,
    signed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);